# -*- ispell-local-dictionary: "english" -*-

#+TITLE: Lokavaluto's LokAPI

LokAPI is a javascript library intended to be used in mobile
applications or web application to abstract all logics with
lokavaluto's server.


* Adding =lokapi= to your project

From the root of your project:

#+begin_src sh
npm install --save @lokavaluto/lokapi
#+end_src

Or better, as =@lokavaluto/lokapi= is still in early release,

#+begin_src sh
npm install --save Lokavaluto/lokapi#master
#+end_src

To be sure to get the latest version, relaunch this last command
whenever you want to update.

* Setting up =lokapi=

** Subclassing main LokAPIAbstract

Please note that an important part of the following is already
packaged in package =@lokavaluto/lokapi-browser= (for node and browser
support), and thus allow you to quick-start your projects with less
code. Here's a link to the project page of
[[https://github.com/Lokavaluto/lokapi-browser][lokapi-browser]] and how to use it, with an example.

Lokapi will require a way to make HTTP request, access to a permanent
store, or various other tasks. Depending on your platform or
environment, you might have different way to implement these.

To inject these exchangeable dependency, you are invited to subclass
LokAPIAbstract and define these objects:

- BackendFactories :: A mapping of currency backends loaded
- httpRequest :: an implementation of =HTTPRequest=
- base64Encode :: a function to encode a string to base64
- persistentStore :: an object implementing this interface:

    #+begin_src typescript
    export interface IPersistentStore {
        get(key: string, defaultValue?: string): string
        set(key: string, value: string): void
        del(key: string): void
    }
    #+end_src

- (optional) requestLogin :: a function to trigger a login screen when
  automatic authorization fails or when no automatic autorization data
  exists. This will be triggered only if a protected request is made
  on the administration backend side.
- (optional) requestLocalPassword :: a function for backends to
  trigger a request to the user for a password that is meant
  to be kept locally on the device. This is typically used before
  payment with some backends (to see an example see package
  =lokapi-backend-comchain=), or administrative tasks. And takes
  usually the form of a popup.

** Instanciating lokapi

On instantiation time, =LokAPI= class will require you to provide:

  - host :: as a =string= (example: "lokavaluto.fr")

  - database :: as a =string= (example: "myodoodb")


*** Example for node


Using node's core =https= as HTTP requestion implementation:


#+begin_src typescript

import http from "http"
import https from "https"

import { VueCookieNext } from 'vue-cookie-next'
import { LokAPIAbstract, e as LokAPIExc, t as LokAPIType } from "@lokavaluto/lokapi"

import cyclos from '@lokavaluto/lokapi-backend-cyclos'


class cookieStore implements LokAPIType.IPersistentStore {
  constructor() {
    VueCookieNext.config({ expire: '7d' })
  }
  get(key: string, defaultValue?: string): string {
    let value = VueCookieNext.getCookie("lokapi_" + key)
    // XXXvlab: CookieViewNext is JSON.parsing string sometimes and this
    // breaks interface !
    if (value !== null && typeof value === "object") {
        return JSON.stringify(value)
    }
    return value
  }
  set(key: string, value: string): void {
    VueCookieNext.setCookie("lokapi_" + key, value)
  }
  del(key: string): void {
    VueCookieNext.removeCookie("lokapi_" + key)
  }
}

const requesters: any = { http, https }

class NodeLokAPI extends LokApiAbstract {

    BackendFactories = {
        cyclos,
    }

    httpRequest = (opts: LokAPIType.coreHttpOpts) => {
        const httpsOpts = {
            host: opts.host,
            path: opts.path,
            method: opts.method,
            ...opts.headers && { headers: opts.headers },
            ...opts.port && { port: opts.port }
        }
        const requester = requesters[opts.protocol]
        if (!requester) {
            throw new Error(`Protocol ${opts.protocol} unsupported by this implementation`)
        }
        return new Promise((resolve, reject) => {
            let req = requester.request(httpsOpts, (res: any) => {
                const { statusCode } = res

                let rawData = ''

                res.on('data', (chunk: any) => { rawData += chunk })
                res.on('end', () => {
                    if (!statusCode || statusCode.toString().slice(0, 1) !== '2') {
                        res.resume();
                        reject(new LokAPIExc.HttpError(statusCode, res.statusMessage, rawData, res))
                        return
                    } else {
                        if (opts.responseHeaders) {
                            for (const header in res.headers) {
                                opts.responseHeaders[header] = res.headers[header]
                            }
                        }
                        resolve(rawData)
                    }
                })
            })

            if (opts.data) {
                if (typeof opts.data !== "string")
                    opts.data = JSON.stringify(opts.data)
                req.write(opts.data)
            }
            req.end()
            req.on('error', (err: any) => {
                console.error(`Encountered an error trying to make a request: ${err.message}`);
                reject(new LokAPIExc.RequestFailed(err.message))
            })
        })
    }

    base64Encode = (s: string) => Buffer.from(s).toString('base64')
    persistentStore = new cookieStore()
}


if (!process.env.VUE_APP_LOKAPI_HOST) {
    throw new Error("Please specify VUE_APP_LOKAPI_HOST in '.env'")
}


if (!process.env.VUE_APP_LOKAPI_DB) {
    throw new Error("Please specify VUE_APP_LOKAPI_DB in '.env'")
}


var lokAPI = new LokAPI(
    process.env.VUE_APP_LOKAPI_HOST,
    process.env.VUE_APP_LOKAPI_DB,
)
#+end_src


*** Example for =nativescript=

Using =@nativescript-community/https= as HTTP request implementation:

Note that this example couldn't be thoroughly tested as much as
it should. Use with caution.

#+begin_src typescript
  import * as https from '@nativescript-community/https';

  import { LokAPIAbstract, e as LokAPIExc, t as LokAPIType } from "@lokavaluto/lokapi"

  import { getString, remove as removeSetting, setString } from '@nativescript/core/application-settings';

  import cyclos from '@lokavaluto/lokapi-backend-cyclos'


  class applicationSetting implements LokAPIType.IPersistentStore {
      get(key: string, defaultValue?: string): string {
          return getString("lokapi_" + key, defaultValue)
      }
      set(key: string, value: string): void {
          setString("lokapi_" + key, value)
      }
      del(key: string): void {
          removeSetting("lokapi_" + key)
      }
  }


  class NativeLokAPI extends LokAPIAbstract {

      BackendFactories = {
          cyclos,
      }

      httpRequest = async (opts: LokAPIType.coreHttpOpts) => {
          const nativeRequestOpts = {
              url: opts.protocol + "://" + opts.host + opts.path,
              method: opts.method,
              headers: opts.headers,
              body: opts.data,
              useLegacy: true,
          }
          let response
          try {
              response = await https.request(nativeRequestOpts)
          } catch (err) {
              console.error(
                  `Encountered an error trying to make a request: ${err.message}`)
              throw new LokAPIExc.RequestFailed(err.message)
          }

          const statusCode = response.statusCode;
          let rawData = await response.content.toStringAsync();

          if (!statusCode || statusCode.toString().slice(0, 1) !== '2') {
              throw new LokAPIExc.HttpError(statusCode, response.reason, "", response)
          }

          if (opts.responseHeaders) {
              for (const header in response.headers) {
                  opts.responseHeaders[header] = response.headers[header]
              }
          }

          return rawData
      }

      base64Encode = base64Encode
      persistentStore = new applicationSetting()
  }


  var lokAPI = new NativeLokAPI(APP_HOST, APP_DB)

#+end_src


* Usage

** Basic usage

*** Login

You must log in to the server with an existing Odoo Lokavaluto
account:

#+begin_src typescript
await lokApi.login("myuser", "mypassword")
#+end_src


*** Accessing accounts

We assume that you've instanciated =LokAPI= as stated in the previous
section, and you have logged in.

#+begin_src typescript
let accounts = await lokAPI.getAccounts()

let balance = await accounts[0].getBalance()
let symbol= await accounts[0].getSymbol()

console.log(`balance in first account: ${balance} ${symbol}`)
#+end_src

- =backend.getAccounts()= is the list of accounts in that connection
  (warning, this is a promise).

- =account.getBalance()= is the balance of the account

- =account.getSymbol()= is the currency symbol for the account


*** Crediting account

You can credit your account thanks to =account.getCreditUrl(amount)=.
This will return an url to finish the purchase of new credits.

#+begin_src typescript
let accounts = await lokAPI.getAccounts()

url = await accounts[0].getCreditUrl(100)

console.log(`I need to follow instructions on $url ` +
            'to purchase credit to store in my account.')
#+end_src


*** Looking for recipients

Recipients are possible receiving end of a transfer of
money. These are connected to contacts in =lokapi=.

We have Pro Recipients which are used for company. And normal
Recipient, any contact non-professional contact. We make
separate search through =lokAPI.searchRecipients(..)= or
=lokAPI.searchProRecipients(..)=.

#+begin_src typescript
let recipients = await lokAPI.searchRecipients("Alain")

recipients.forEach(recipient => {
    console.log(`name: ${recipient.name}`)
})
#+end_src

Note that if you look for an empty string,
=lokAPI.search{,Pro}Recipients("")= will return all favorite recipients.

Recipients are always ordered with favorites first and by name.

You can also grab recipients by url. This url is the identity
url created by odoo. It'll return a list of recipients, one
for each backend you can use to send money.

#+begin_src typescript
let url = "https://myhost.com/fr_FR/partners/foo-bar-13"
let recipients = await lokAPI.getRecipientsFromUrl(url)

recipients.forEach(recipient => {
    console.log(`name: ${recipient.name}`)
})
#+end_src


*** Transfer money between an account to a recipient

Transfering money is done from an account of the logged-in user
to a recipient:

#+begin_src typescript

// Fetch recipients named 'Alain'
let recipients = await lokAPI.searchRecipients("Alain")

await recipients[0].transfer("12", "Dinner Party participation")
#+end_src


*** Requesting contact info on current logged in user

The method =lokAPI.getMyContact()= allows you to get back
your own information.:

#+begin_src typescript

// My own information
let me = await lokAPI.getMyContact()
console.log(`My user name: ${me.name}`)

#+end_src


*** Setting/Unsetting Favorite status of a contact

You can set or unset the "favorite" state of a given contact with the
=lokAPI.setFavorite(..)=, =lokAPI.unsetFavorite(..)=, or
=lokAPI.toggleFavorite(..)= method. This can be used on a recipient
(from =.searchRecipients()=) or a contact (but for now, only
=.getMyContact()= is outputting a contact, and it doesn't make
sense to be your own favorite, does it ?).

It'll not return any value, but the contact will be updated
accordingly.

#+begin_src typescript
let recipients = await lokAPI.searchRecipients("Alain")

await recipients[2].setFavorite()
await recipients[3].unsetFavorite()

console.log(recipients[3].is_favorite) // is expected to be unset

#+end_src


*** List transactions

List past transactions for the current logged in user.

#+begin_src typescript
let transactions = await lokAPI.getTransactions()

for (const tr of transactions) {
    console.log(`  ${tr.date} ${tr.amount} ${tr.currency}`)
}
#+end_src


** Miscellaneous and internal helpers

*** Get the backend list

You can query the =lokapi= to get the backend list available on the
administration backend side. A Backend instance is the main object
whose instance is responsible for a currency domain. You have a
Backend per currency. So in short, =.getBackends()= will give you
the available currencies available.

This function is cached, so it doesn't get updated if you happen
to add a new currency backend in the administration backend.

=.getBackends()= returns an Object mapping a string identifier for the
backend (ie: `cyclos:cyclos.example.com`, `comchain:Lemanopolis`, ...), and
the Backend object instance.

#+begin_src typescript
let backends = await lokAPI.getBackends()

for (const b in backends) {
    console.log(`  Backend ${b}:`, backends[b])
}
#+end_src


*** Direct request to odoo api

You can use =lokapi= instance to query directly the odoo api trough
the =get=, =post=, =put=, =delete= methods and their authenticated
counterparts, =$get=, =$post=, =$put=, =$delete=.

#+begin_src typescript

// All 8 methods have this signature:
// type restMethod = (path: string, data?: JsonData, headers?: { [label: string]: string }): Promise<JsonData>

// Notice that the next call is an example, but you don't need to
// use this endpoint as it is used by the lokAPI.login() and
// manages token for you.
lokAPI.post('/auth/authenticate', {
  api_version: 2,
  db: 'mydb',
  params: ['lcc_app']
}, {
  'Authorization': 'XYZ',
})

lokAPI.$post(`/partner/${userId}`)
lokAPI.$put(`/partner/${userId}/favorite/set`)
lokAPI.$get(`/partner/partner_search`, {
  value: "foo"
})
#+end_src

Please note that =.get(..)= and =.$get(..)= have same prototype
and usage than other function and do not require you to build a query
string as it'll encode in the URL as a querystring the data you've
provided.
